package fon.rs.np.RentACarKlijentMaven.form;

import fon.rs.np.RentACarZajednickiMaven.domen.Iznajmljivanje;
import fon.rs.np.RentACarZajednickiMaven.domen.Korisnik;
import fon.rs.np.RentACarZajednickiMaven.domen.Racun;
import fon.rs.np.RentACarZajednickiMaven.domen.StatusVozila;
import fon.rs.np.RentACarZajednickiMaven.domen.StavkaCenovnika;
import fon.rs.np.RentACarZajednickiMaven.domen.StavkaRacuna;
import fon.rs.np.RentACarZajednickiMaven.domen.Vozilo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import fon.rs.np.RentACarKlijentMaven.kontroler.Kontroler;
import fon.rs.np.RentACarKlijentMaven.tabele.ModelTabeleStavkaRacuna;
import fon.rs.np.RentACarKlijentMaven.tabele.ModelTabeleVozila;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import fon.rs.np.RentACarZajednickiMaven.transfer.Odgovor;

public class IznajmljivanjeForma extends javax.swing.JDialog {

    double ukupno = 0, paket = 0, iznos = 0, total = 0;
    List<StavkaCenovnika> stavke;
    ModelTabeleVozila mtv;
    ModelTabeleStavkaRacuna mti;

    public IznajmljivanjeForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        txtRegistracija.setEditable(false);

        txtUkupno.setText("" + iznos);

        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIznajmljeno = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIznajmi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbKorisnici = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dateVracanje = new com.toedter.calendar.JDateChooser();
        dateIzdato = new com.toedter.calendar.JDateChooser();
        txtRegistracija = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnIznajmi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtUkupno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbKategorije = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtIznosPaketa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIznosVozila = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblZaIznajmljivanje = new javax.swing.JTable();
        btnIzbaci = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtRacun = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Iznajmljivanje");
        setBackground(new java.awt.Color(153, 153, 153));
        setBounds(new java.awt.Rectangle(300, 300, 789, 621));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista kola");

        tblIznajmljeno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIznajmljeno);

        tblIznajmi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblIznajmi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIznajmiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblIznajmi);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Iznajmljivanje");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lista izdatih");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Korisnik");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Paket");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dan izdato");

        dateVracanje.setMinSelectableDate(Date.valueOf(LocalDate.now())
        );

        dateIzdato.setMinSelectableDate(Date.valueOf(LocalDate.now())
        );

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Izabrana kola");

        btnIznajmi.setText("Iznajmi");
        btnIznajmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIznajmiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ukupan iznos:");

        txtUkupno.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dan vracanja");

        cbKategorije.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbKategorijeItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Iznos paketa:");

        txtIznosPaketa.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Iznos vozila:");

        txtIznosVozila.setEditable(false);

        tblZaIznajmljivanje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblZaIznajmljivanje);

        btnIzbaci.setText("Izbaci");
        btnIzbaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciActionPerformed(evt);
            }
        });

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        jLabel12.setText("Iznos računa:");

        txtRacun.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(dateIzdato, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(105, 105, 105)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateVracanje, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(cbKategorije, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnIzbaci)
                                                .addGap(26, 26, 26)
                                                .addComponent(btnIznajmi))
                                            .addComponent(btnDodaj))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIznosPaketa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIznosVozila, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateIzdato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(dateVracanje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbKategorije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtIznosVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtIznosPaketa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnDodaj)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnIznajmi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnIzbaci)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12))
                    .addComponent(txtRacun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblIznajmiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIznajmiMouseClicked
        if (tblIznajmi.getSelectedRow() != -1) {
            ukupno -= iznos;

            Vozilo vozilo = ((ModelTabeleVozila) tblIznajmi.getModel()).vratiVozilo(tblIznajmi.getSelectedRow());
            txtRegistracija.setText(vozilo.getRegistarskiBroj());

            iznos = vozilo.getKategorijaVozila().getCena();
            txtIznosVozila.setText("" + iznos);

            ukupno += iznos;
            txtUkupno.setText("" + ukupno);
        }
    }//GEN-LAST:event_tblIznajmiMouseClicked

    private void btnIznajmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIznajmiActionPerformed
        if (((ModelTabeleStavkaRacuna) tblZaIznajmljivanje.getModel()).getIznajmljeno().size() == 0)
            JOptionPane.showMessageDialog(this, "Molimo izaberite vozilo za izdavanje");
        else {
            Korisnik korisnik = (Korisnik) cbKorisnici.getSelectedItem();
            List<StavkaRacuna> lista = listaStavki(korisnik);
            Racun r = new Racun(Date.valueOf(LocalDate.now()),
                    0.85 * total, 0.15 * total, total,
                    korisnik,
                    lista);
            Odgovor o = Kontroler.getInstance().iznajmiVozilo(r);
            if(o.isUspesno()) {
                tblZaIznajmljivanje.setModel(new ModelTabeleStavkaRacuna(new ArrayList<StavkaRacuna>()));
                lista = ((Racun) o.getOdgovor()).getStavkaRacuna();
                for(StavkaRacuna sr : lista) {
                    mti.dodajIznajmljeno(sr);
                    Kontroler.getInstance().getGf().azuriraj(sr.getVozilo());
                }
            }
        }
    }//GEN-LAST:event_btnIznajmiActionPerformed

    private void cbKategorijeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbKategorijeItemStateChanged
        ukupno -= paket;

        paket = ((StavkaCenovnika) cbKategorije.getSelectedItem()).getCena();
        txtIznosPaketa.setText("" + paket);

        ukupno += paket;
        txtUkupno.setText("" + ukupno);
    }//GEN-LAST:event_cbKategorijeItemStateChanged

    private void btnIzbaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciActionPerformed
        if (tblZaIznajmljivanje.getSelectedRow() != -1) {
            StavkaRacuna izbaci = ((ModelTabeleStavkaRacuna) tblZaIznajmljivanje.getModel()).vrati(tblZaIznajmljivanje.getSelectedRow());
            double cena = izbaci.getIznosSaPDV();
            mtv.dodajVozilo(izbaci.getVozilo());

            ((ModelTabeleStavkaRacuna) tblZaIznajmljivanje.getModel()).izbaci(tblZaIznajmljivanje.getSelectedRow());
            total -= cena;
            txtRacun.setText("" + total);
        } else
            JOptionPane.showMessageDialog(this, "Niste izabrali");
    }//GEN-LAST:event_btnIzbaciActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        if (!txtRegistracija.getText().equals("") && dateIzdato.getDate() != null && dateVracanje.getDate() != null
                && dateIzdato.getDate().before(dateVracanje.getDate())) {
            Vozilo v = mtv.vratiVozilo(tblIznajmi.getSelectedRow());
            Korisnik korisnik = (Korisnik) cbKorisnici.getSelectedItem();

            int razlika = razlikaUDatumima();
            ukupno *= razlika;
            
            StavkaRacuna novo = new StavkaRacuna(0.85 * ukupno, 0.15 * ukupno, ukupno,
                    korisnik, v,
                    new Iznajmljivanje(korisnik, v, dateIzdato.getDate(), dateVracanje.getDate()));

            ((ModelTabeleStavkaRacuna) tblZaIznajmljivanje.getModel()).dodajIznajmljeno(novo);
            mtv.izbrisiVozilo(tblIznajmi.getSelectedRow());

            total += ukupno;
            txtRacun.setText("" + total);
            reset();
        } else
            JOptionPane.showMessageDialog(this, "Molimo unesite ispravne podatke");
    }//GEN-LAST:event_btnDodajActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzbaci;
    private javax.swing.JButton btnIznajmi;
    private javax.swing.JComboBox<StavkaCenovnika> cbKategorije;
    private javax.swing.JComboBox<Korisnik> cbKorisnici;
    private com.toedter.calendar.JDateChooser dateIzdato;
    private com.toedter.calendar.JDateChooser dateVracanje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblIznajmi;
    private javax.swing.JTable tblIznajmljeno;
    private javax.swing.JTable tblZaIznajmljivanje;
    private javax.swing.JTextField txtIznosPaketa;
    private javax.swing.JTextField txtIznosVozila;
    private javax.swing.JTextField txtRacun;
    private javax.swing.JTextField txtRegistracija;
    private javax.swing.JTextField txtUkupno;
    // End of variables declaration//GEN-END:variables

    private void populate() {
        List<Korisnik> korisnici = Kontroler.getInstance().vratiKorisnike();
        for (Korisnik k : korisnici) {
            cbKorisnici.addItem(k);
        }

        List<Vozilo> vozila = Kontroler.getInstance().vratiSlobodnaVozila(new Vozilo());
        mtv = new ModelTabeleVozila(vozila);
        tblIznajmi.setModel(mtv);

        List<StavkaRacuna> iznajmljena = Kontroler.getInstance().vratiIznajmljeno(new StavkaRacuna());
        mti = new ModelTabeleStavkaRacuna(iznajmljena);
        tblIznajmljeno.setModel(mti);

        stavke = Kontroler.getInstance().ucitajListuCenovnika(new StavkaCenovnika());
        for (StavkaCenovnika c : stavke) {
            cbKategorije.addItem(c);
        }
        
        tblZaIznajmljivanje.setModel(new ModelTabeleStavkaRacuna(new ArrayList<StavkaRacuna>()));
    }

    private void reset() {
        txtRegistracija.setText("");
        txtIznosPaketa.setText("");
        txtIznosVozila.setText("");
        txtUkupno.setText("");
        dateIzdato.setDate(null);
        dateVracanje.setDate(null);
    }

    private List<StavkaRacuna> listaStavki(Korisnik korisnik) {
        List<StavkaRacuna> lista = ((ModelTabeleStavkaRacuna) tblZaIznajmljivanje.getModel()).getIznajmljeno();

        for (StavkaRacuna sr : lista) {
            sr.setKorisnik(korisnik);
            sr.getVozilo().setStatusVozila(StatusVozila.ZAUZETO);
            System.out.println(sr);
        }

        return lista;
    }

    private int razlikaUDatumima() {
        LocalDate izdato = dateIzdato.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate vracanje = dateVracanje.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        return vracanje.getDayOfYear() - izdato.getDayOfYear();
    }

}
